apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: pvc123
  containers:
    - name: c1
      image: nginx:1.14.2
      volumeMounts:
        - mountPath: "/abc"
          name: myvol
