apiVersion: v1
kind: Pod
metadata:
  name: single-pod
  namespace: custom
  labels:
    app: single-pod
spec:
  # matchLabels:
  #   app: single-pod-match
  containers:
    - name: container1
      image: nginx:1.14.2
      ports:
        - containerPort: 80
