apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db-service-pod
spec:
  containers:
  - name: db-service-pod
    image: mysql:latest
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: root
    ports:
      - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mydbinst
spec:
  selector:
    app: db-service-pod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306