apiVersion: v1
kind: Pod
metadata:
  name: lab1
  labels:
    name: lab1
spec:
  containers:
  - name: lab1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
